# Site
name: 'Kinderwunschklinik Waghäusel'
logo: 'assets/images/favicon2.png'
favicon: 'assets/images/favicon5.png'
baseurl: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
      
    theodor:
      name:           Dr. Theodor Phillip
      avatar:         assets/images/theodor.png
      bio:            "Meine Aufgabe als Mediziner ist es, kinderlosen Paaren neue Möglichkeiten zu eröffnen."

    roman:
      name:           Dr. Roman Tisch
      avatar:         assets/images/roman.png
      bio:            "Wenn die Möglichkeiten erschöpft scheinen, kommen wir zum Einsatz."

    anna:
      name:           Dr. Anna Gramm
      avatar:         assets/images/anna.png
      bio:            "Falls die Natur einen Fehler macht, sind wir die Helfer."

    felix:
      name:           Felix Ochse
      avatar:         assets/images/felix.png
      bio:            "Die Möglichkeiten der Technik begeistern mich immer wieder."

    sophia:
      name:           Sophia Weschenfelder
      avatar:         assets/images/sophia.png
      bio:            "Wenn wir Paaren den Kinderwunsch erfüllen können, ist das die größte Belohnung in meinem Beruf."
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]